export const era = [
  {
    type: 'radio',
    name: 'Era',
    value: 'Steinzeit',
    id: 'Stone Age',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Era',
    value: 'Bronzezeit',
    id: 'Bronze Age',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Era',
    value: 'Eisenzeit',
    id: 'Iron Age',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Era',
    value: 'Antike',
    id: 'Antiquity',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Era',
    value: 'Mittelalter',
    id: 'Middle Age',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Era',
    value: 'Maschinenzeitalter',
    id: 'Maschine Age',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Era',
    value: 'Digitalzeitalter',
    id: 'Information Age',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Era',
    value: 'Zukunft',
    id: 'Future',
    checked: false,
  },
]

export const locations = [
  {
    type: 'radio',
    name: 'Location',
    value: 'Asien',
    id: 'Asia',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Location',
    value: 'Afrika',
    id: 'Africa',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Location',
    value: 'Nordamerika',
    id: 'North America',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Location',
    value: 'Südamerika',
    id: 'South America',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Location',
    value: 'Europa',
    id: 'Europe',
    checked: false,
  },
  {
    type: 'radio',
    name: 'Location',
    value: 'Australien',
    id: 'Australia',
    checked: false,
  },
]

export const textinputs = [
  {
    p_tag_text: 'What kind of clothes do you like',
    type: 'text',
    name: 'Clothes',
    placeholder: 'Leather shoes, Kimono, Saris or ...',
    id: 'Clothes',
  },
  {
    p_tag_text: 'How old are you?',
    type: 'text',
    name: 'Old',
    placeholder: '20, 58, ...',
    id: 'Old',
  },
]

export const hobby = [
  'Bier',
  'Rakete',
  'Fußball',
  'Hund',
  // 'Fitness',
  // 'Musick',
  // 'Fotografieren',
  // 'Bloggen',
  // 'Shopping',
  // 'Essen gehen',
  // 'Kino',
  // 'Fußball',
  // 'Tennis',
  // 'Schwimmen',
  // 'Tauchen',
  // 'Wandern',
  // 'Lesen',
  // 'Yoga',
  // 'Kochen',
  // 'Tanzen',
  // 'Bowling',
  // 'Puzzeln ',
  // 'Backen ',
  // 'Joggen',
]
